### ISSUE TITLE
Error displayed for all players when module enabled

### ISSUE THREAD

**Issue by pdf** [delVhariant/illumination#10]
All players receive an error notification upon loading into a scene:
```
User <UserID> lacks permission to update Scene <SceneID>
```

I'd rather not have to grant users access to modify scenes, is this required for the module to function? And if it is, the required settings should probably be documented. This has been reported many times on the Foundry Discord, but I couldn't find anyone who posted a solution.

**Comment by delVhariant** [comment]
I suspect I have something happening for all users that should only be occurring for the GM. I'll take a look and try to push a fix ASAP

**Comment by delVhariant** [comment]
@pdf This should be fixed in the latest update, thanks for bringing it to my attention!

**Comment by pdf** [comment]
Working great, thank you for the quick fix!
