### ISSUE TITLE
Color Change Error

### ISSUE THREAD

**Issue by bibicvc** [delVhariant/illumination#12]
When moving from dawn to day to dusk to night, the color and darkness level change as intended for the DM. 

For the player, the darkness level changes correctly but the color change is inconsistent. Sometimes the color does not change. At other times the color changes to the wrong color. This is fixed if the color change is also accompanied by a change in global illumination. I have attached a picture of my settings in case this is relevant, but fiddling with any setting apart from "Link Global Illumination" does not appear to change this behavior. The intended behavior is that the color changes for the player as it does for the DM.

![image](https://user-images.githubusercontent.com/68487801/89695181-6fa0a500-d8e9-11ea-9a57-5bd3491010dc.png)

**Comment by delVhariant** [comment]
Hi @bibicvc, the latest version pushed to Foundry (0.3.1) should fix this issue, can you confirm you're still getting the issue on that version?

**Comment by bibicvc** [comment]
Yes, I am using 0.3.1 and still get this error. To be more precise in reproducing it:

Click on darkness - normal behavior
Click on darkness, then dusk - normal behavior.
Click on darkness, then dawn - normal behavior
Click on darkness, then daylight - normal behavior
Click on darkness, then dusk, then dawn - dawn has expected illumination but dusk color.
Click on darkness, then dawn, then dusk - dusk has expected illumination but dawn color
Click on darkness, then daylight, then dawn - dawn has daylight illumination and color
Click on darkness, then daylight, then dusk - dusk has daylight illumination and color

**Comment by delVhariant** [comment]
Ah thanks, I understand. I'll try and get it fixed ASAP

**Comment by delVhariant** [comment]
@bibicvc , I've just released the fixed version on Foundry, please let me know if you continue to have any issues

**Comment by bibicvc** [comment]
Works great, thanks for the awesome mod!
