### ISSUE TITLE
BUG - The module broke the scenes on version 0.7.1 of foundry

### ISSUE THREAD

**Issue by p4535992** [delVhariant/illumination#15]
**Environment Details:**

Foundry VTT Version: 0.7.1
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.95
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

It's a strange behaviour, after the module is enable, many of my scene have lost their customization settings.

There is no web console exception.

These are the steps for replicate the issue:

0) The module is disable at the start
1) Create a new scene
2) Select a new file for the background of the scene (in my use case it's a webm file)
3) Modify the background size scale from "1" to "2"
4) Save the scene
5) Refresh the page it's seem all good
6) Enable the module
7) After the refresh the scene it's "broken" like it's was cut and after a second refesh the scene it's reload with the original image  scale size set to "1" not "2"

**Comment by delVhariant** [comment]
I've not tested on 0.7.x yet, so I'm not entirely sure what could be happening.

I'm aiming to do some testing this week though, so hopefully I can replicate/fix soon

**Comment by delVhariant** [comment]
Hi @p4535992 and apologies for the delay on getting to this.
I've attempted to replicate the issue on 0.7.2, but haven't been able to.

Are you still seeing the issue on 0.7.2? My module doesn't interact with the background scalding at all, so I'm wondering if there was possibly a bug in 0.7.1 that caused the behavior you were seeing.

**Comment by p4535992** [comment]
Problaby resolved on 0.7.2. Ty for the input. I close the ticket.
