### ISSUE TITLE
Error When transitioning to Dusk or Dawn

### ISSUE THREAD

**Issue by yoshikidneo** [delVhariant/illumination#22]
dynamic-illumination.js:70 Uncaught (in promise) TypeError: Cannot set property 'unexploredColor' of undefined
    at dynamic-illumination.js:70

This pops up whenever I use the module. Any idea of the fix?

**Comment by Ragash** [comment]
i second this

**Comment by delVhariant** [comment]
Is this version 0.7.5 or 0.7.6? I think those values only exist in 0.7.6, I forgot that when I set the min version

**Comment by Ragash** [comment]
0.7.6!

**Comment by delVhariant** [comment]
@Ragash @yoshikidneo I just found that a typo had snuck in, sorry about that.
I've pushed a very small release to correct it, updating should stop the error.

**Comment by yoshikidneo** [comment]
Awesome thanks for that quick turn around, ill download the update when i get home from work!
