### ISSUE TITLE
[bug] Dynamic Illumination is allowing PCs to see through walls

### ISSUE THREAD

**Issue by SamF111** [delVhariant/illumination#23]
foundryvtt version 0.7.7, but it occured in 0.7.6 too
5th edition version 1.1.1
DI version 0.7.61

Player point of view with only DI enabled:
![image](https://user-images.githubusercontent.com/5872655/99113782-b63c2480-25e7-11eb-801f-d495cc19dae4.png)

Player point of veiw with DI disabled:

![image](https://user-images.githubusercontent.com/5872655/99113713-9c9add00-25e7-11eb-8b35-8159e8ddf022.png)

This happens on multiple scenes, but only seems to happen on very large maps. Does not happen on small test scenes...

**Comment by NutritiousCookie** [comment]
Also getting this issue. Unlit areas will appear as the Darkness Level of the map, even if they are not revealed.

**Comment by jalensailin** [comment]
Also getting this issue

**Comment by delVhariant** [comment]
I think this was caused by me changing the "unexploredColor" flag.
Sorry about that, the new version I've published should fix it, but you may need to reset fog of war.

**Comment by caerandir** [comment]
Can confirm that this is fixed!
