### ISSUE TITLE
Got this error of "lights" being set to null

### ISSUE THREAD

**Issue by yoshikidneo** [delVhariant/illumination#25]
Happens on loading my world

Uncaught (in promise) TypeError: Cannot read property 'lights' of null
    at LightingLayer.refresh (foundry.js:38347)
    at dynamic-illumination.js:73

**Comment by delVhariant** [comment]
Can you confirm this is on the 0.7.7 version of the module?

**Comment by yoshikidneo** [comment]
Can confirm, I have version 0.7.7. I deleted and reinstalled and still have that error. I don't believe it is doing anything to my performance at all, it only happens on load.

I've also encountered a new issue, for whatever reason my transition buttons are not doing what they usually do. If I click a button, it will change the darkness level of the map, but it won't actually show on the map, only in the settings that it has changed. Any lights I have set for a certain darkness level begin to illuminate, but the map stays bright, the color doesn't change, and the vision of tokens remains. I have confirmed that Global illumination turns off at a certain threshold, but it doesn't do anything even with a reload of the map.

Without the module enabled, the transitions from day to night work as intended.

I have a screen capture of me clicking the buttons and showing the settings change without actually seeing the changes if you want me to send a link via google drive.

**Comment by dev7355608** [comment]
`LightingLayer.refresh` (and `refresh` on any layer) must not be called before the "canvasReady" event. I suggest:
```diff
- Hooks.once("canvasInit", () => {
+ Hooks.on("canvasReady", () => {
```
It should probably be `on` and not `once`, otherwise the hook is only executed for the initial scene but never again when switching scenes. It looks like the code needs to be called for each scene.

**Comment by yoshikidneo** [comment]
> `LightingLayer.refresh` (and `refresh` on any layer) must not be called before the "canvasReady" event. I suggest:
> 
> ```diff
> - Hooks.once("canvasInit", () => {
> + Hooks.on("canvasReady", () => {
> ```
> 
> It should probably be `on` and not `once`, otherwise the hook is only executed for the initial scene but never again when switching scenes. It looks like the code needs to be called for each scene.

I made those changes, and the error has gone away! Thanks!
